/*******************************************************************************
*                                                                              *
*                         CanonicalEmptySnapshot                               *
*                                                                              *
*******************************************************************************/

// canonical binary snapshot of a freshly initialised, empty SDS_DataStore

// ╔══════════════════════════════════════════════════════════════════════════╗
// ║  WARNING — DO NOT REGENERATE THIS SNAPSHOT CASUALLY                      ║
// ║                                                                          ║
// ║  this byte array encodes the internal json-joy CRDT node-Id space that   ║
// ║  ALL peers share.  every store loaded via SDS_DataStore.fromScratch()    ║
// ║  starts from exactly these bytes.  if the snapshot is replaced with      ║
// ║  freshly generated bytes, the new node-Id space will be different from   ║
// ║  the old one, making ALL existing persisted stores and patches           ║
// ║  PERMANENTLY INCOMPATIBLE with stores created from the new snapshot.     ║
// ║                                                                          ║
// ║  regeneration is only ever justified when:                               ║
// ║    1. the SDS entry schema changes (new top-level CRDT fields), AND      ║
// ║    2. you accept that all existing persisted data will be abandoned.     ║
// ║                                                                          ║
// ║  The generation script is in packages/core/scripts/generate-canonical-   ║
// ║  snapshot.test.ts.  See the long comment at the top of that file for     ║
// ║  prerequisites and consequences.                                         ║
// ╚══════════════════════════════════════════════════════════════════════════╝

export const CanonicalEmptySnapshot = new Uint8Array([
  31, 139, 8, 0, 177, 131, 174, 105, 0, 3, 99, 96, 96, 82, 111, 12, 112, 172, 96, 119, 205, 43, 41, 202, 76, 45, 110, 244, 119, 174, 80, 49, 128, 2, 93, 48, 97, 2, 34, 44, 96, 92, 24, 104, 244, 115, 77, 241, 206, 204, 75, 105, 244, 101, 72, 201, 44, 73, 205, 77, 245, 73, 76, 74, 205, 105, 244, 81, 104, 244, 110, 72, 241, 204, 75, 203, 111, 244, 116, 168, 224, 240, 245, 244, 117, 13, 169, 44, 72, 109, 244, 80, 104, 116, 111, 168, 224, 12, 75, 204, 41, 77, 5, 107, 115, 85, 104, 116, 105, 108, 116, 78, 201, 203, 207, 75, 37, 202, 70, 195, 70, 91, 55, 136, 141, 54, 16, 27, 43, 248, 242, 75, 75, 82, 139, 2, 114, 18, 147, 129, 214, 231, 149, 52, 90, 43, 52, 90, 49, 44, 170, 224, 6, 11, 123, 2, 85, 120, 166, 16, 231, 151, 10, 14, 255, 162, 148, 212, 34, 239, 212, 202, 164, 68, 3, 168, 71, 44, 20, 26, 205, 27, 27, 205, 82, 75, 138, 18, 139, 51, 32, 30, 50, 64, 246, 144, 190, 66, 163, 30, 138, 135, 116, 20, 26, 181, 27, 27, 181, 136, 247, 144, 81, 163, 10, 212, 67, 202, 56, 60, 164, 164, 208, 168, 72, 177, 135, 12, 161, 30, 146, 87, 104, 148, 107, 108, 148, 173, 224, 203, 201, 47, 46, 209, 77, 204, 75, 209, 77, 203, 47, 205, 75, 1, 123, 77, 14, 201, 103, 178, 10, 50, 200, 254, 146, 82, 144, 108, 148, 0, 123, 138, 241, 202, 175, 89, 83, 55, 29, 94, 204, 30, 8, 0, 64, 93, 64, 8, 53, 2, 0, 0,
])
